export const ADD_TASK_LOAD = "ADD_TASK_LOAD";
export const ADD_TASK_SUCCESS = "ADD_TASK_SUCCESS";
export const ADD_TASK_FAIL = "ADD_TASK_FAIL";

export const GET_TASKS_LOAD = "GET_TASKS_LOAD";
export const GET_TASKS_SUCCESS = "GET_TASKS_SUCCESS";
export const GET_TASKS_FAILURE = "GET_TASKS_FAILURE";

export const DELETE_TASK_LOAD = "DELETE_TASK_LOAD";
export const DELETE_TASK_SUCCESS = "DELETE_TASK_SUCCESS";
export const DELETE_TASK_FAIL = "DELETE_TASK_FAIL";

export const DONE_TASKS_LOAD = "DONE_TASKS_LOAD";
export const DONE_TASKS_SUCCESS = "DONE_TASKS_SUCCESS";
export const DONE_TASKS_FAIL = "DONE_TASKS_FAIL";

export const UPDATE_TASK_LOAD = "UPDATE_TASK_LOAD";
export const UPDATE_TASK_SUCCESS = "UPDATE_TASK_SUCCESS";
export const UPDATE_TASK_FAIL = "UPDATE_TASK_FAIL";